### ISSUE TITLE
Mesh Opacity not working

### ISSUE THREAD

**Issue by clownfetus** [xxSeys1/Godot_ColoredColissionShapes#1]
I'm using Godot 4.1.1-stable on GLES3 mode and Mesh Opacity seems to not work.

I tested with a green 8x8 square as a texture with texture transparency on and the color as white at 128 alpha to get the following:
![intersection](https://github.com/xxSeys1/Godot_ColoredColissionShapes/assets/47909358/6c931fe8-208b-4550-85fe-577d4377b713)

What I was intending to create was a transparent green cube where I can see the intersecting purple cube through it. I tried a fully transparent, fully black and fully white texture and in none of these cases was the Mesh Opacity value affecting anything. Strangely, in the previous image's test case, dropping the alpha one more point to 127 makes the mesh disappear fully. I then tried with a partially transparent white square as the texture and no matter the color alpha, the mesh was invisible as long as texture transparency was enabled.

Thanks for your work in adding this idea to Godot 4, btw.

**Comment by xxSeys1** [comment]
Wait let me look into this. I never tested in any other renderer than Vulkan, so it's most likely some incompatibility.

**Comment by xxSeys1** [comment]
Ok I think I fixed it, is this:

![image](https://github.com/xxSeys1/Godot_ColoredColissionShapes/assets/111653551/9c99d649-3930-468a-b0ed-53c479f5f658)

what you were trying to achieve?

**Comment by clownfetus** [comment]
Yep, precisely.

**Comment by xxSeys1** [comment]
Ok. Had something to do with the transparency mode I was using not working like in Vulkan when using GLES3. I think I fixed it, lemme put that on GitHub

**Comment by clownfetus** [comment]
Ok, the color alpha works great now, thanks.
